base_json_format = [
    {
        "$iSupplier": "Private Label",
        "$iBrand": "",
        "$iProduct_Name": "",
        "$iProduct_Type": "Optical",
        "$iProduct_Gender": "Unisex",
        "$iProduct_Material": "",
        "$iProduct_Style": "",
        "$iProduct_SKU": "",
        "$iProduct_Shape": "",
        "$iProduct_Des": "",
        "$iProduct_Model_Des": "",
        "$iFrame_Code": "",
        "$iFrame_Color": "",
        "$iFrame_Front_Color": "",
        "$iFrame_Bridge": "",
        "$iFrame_Bridge_Design": "",
        "$iFrame_Temple": "",
        "$iFrame_Temple_Material": "",
        "$iFrame_Rx_Able": "",
        "$iFrame_Char": "",
        "$iLens_Size_w": "",
        "$iLens_Size_h": "",
        "$iLens_Size_dia": "",
        "$iLens_Type": "",
        "$iLens_Color": "",
        "$iLens_Base": "",
        "$iLens_Material": "",
        "$iLens_Properties": "",
        "$iLens_Char": "",
        "$iFrame_Availability": "Available",
        "$iStock_Quantity": "",
        "$iFrame_Price": "",
        "$iFrame_Retail": "",
        "$iManufacture": "",
        "$iFrame_IMAGE": "https://masterdb.co.uk/images/awaiting.jpg",
        "$iFrame_IMG_Mark": "0",
        "$iProduct_Model": "",
        "$iCountry": "",
        "$iProduct_Front_Material": "",
        "$iProduct_UPC": "",
        "$iProduct_FB_ID": "",
        "Error": "",
        "$iModelURL": "",
        "$iBrandURL": ""
    }
]